sudo: false
language:
  - node_js
node_js:
  - "stable"
install:
  - npm ci
cache:
  directories:
    - "node_modules"
services:
  - mongodb
script:
  - npm run lint
  - npm run test:coveralls
notifications:
  email: false
